** [[https://www.quantlab.com][Quantlab]]
| Title                | Organization                        | Period         |
|----------------------+-------------------------------------+----------------|
| *Software Developer* | Core Research                       | 2024 - Present |
| *Software Developer* | Futures Engineering/Alpha-Recon     | 2023 - 2024    |
| *Software Developer* | Engineering Modeling and Simulation | 2022 - 2023    |
| *Software Developer* | HPC/Edge-Dev                        | 2021 - 2022    |

 - Played a pivotal role in integrating various machine learning
   frameworks into Quantlab's cutting-edge trading/research platform,
   enhancing its research-to-production functionality. Demonstrated the
   platform's capabilities by developing agnostic deep learning models for
   pricemovement prediction through limit order book data.

 - Overhauled the model engine of Quantlab's newest trading and
   research platform, focusing on improving calculation accuracy,
   consistency, and performance visibility. This enabled more
   effective performance optimization and ensured the verifiability of
   research calculations.

 - Authored a Python library compatible with the ~Executor~ protocol
   from the ~concurrent.futures~ module, facilitating efficient data
   sampling, fitting, and simulation workflows, sometimes composed of
   nearly a million tasks. Optimized the model fitting process,
   cutting down time to one-third of the original and achieving peak
   data read rates over 600 GB/s.

 - Developed low-latency C++ feed handlers for multiple US equity
   exchanges and designed adapters to integrate modern feed handlers
   with legacy systems, significantly improving data processing speed
   and reliability.

 - Implemented data aggregation and processing pipelines using Python
   and C++. Designed and developed a unique application for the
   isomorphic transformation of binary protocol specifications across
   multiple proprietary DSLs and JSON, employing Racket for the
   implementation.
