#+OPTIONS: toc:nil H:10 tex:t num:f author:nil date:nil
#+STARTUP: hidestars indent
#+INCLUDE: personal-info.org
#+LateX_HEADER: \usepackage{resume}
#+LateX_HEADER: \hypersetup{hidelinks}
#+LateX_CLASS_OPTIONS: [letterpaper]

#+TITLE:{{{FULL}}}

| {{{ADDRESS}}} | {{{PHONE}}} | {{{EMAIL}}} |


* SUMMARY

  I am a computational engineer/scientist primarily focused on
  algorithm and software development for the numerical solution of
  differential-algebraic equations, ordinary differential equations, 
  partial differential equations, and linear and nonlinear algebraic
  equations pertaining to models of physical and industrial processes,
  especially those involving fluid dynamics and coupled
  fluid-structure interactions and  heat transfer.  I have Additional
  interests in the areas of symbolic computing, automatic
  differentiation, model order reduction, formal verification for
  software development, and linguistics. 

  
* EMPLOYMENT HISTORY

** Halliburton Engineering Services, Inc.

| *Technical Advisor*                | Production Enhancement | 2012-Present |
| *Principal Technical Professional* | Production Enhancement |    2010-2012 |

Development and implementation of algorithms for the simulation of
hydraulic fracturing,  for the automatic classification and index
reduction of systems of differential-algebraic equations based on a
graph-theoretic analysis of the system's structure, development of
a template library for automatic differentiation, development of a
high-performance computing framework for the simulation of
disparate but tightly coupled physical models, development of
physical models for the numerical simulation of complex physical
systems related to hydraulic fracturing and other production
enhancement processes, development of best practices
recommendations for the development of scientific computing and
computer aid engineering software. 

** Analysis and Design Applications Company (CD-adapco)

   | *Lead Engineer*   | Engineering Services | 2007 - 2010 |
   | *Senior Engineer* | Engineering Services | 2006 - 2007 |

   Consulting services in the area of thermal and fluid analysis of
   engineering systems for the Automotive, Marine, Nuclear, and Oil
   and Gas industries using CD-adapco's state-of-the-art software, and
   clusters, coupled with third party software and custom
   purpose-built numerical models. 

** University of California, Davis

   | *Postdoctoral Researcher* | Center for Computational Science and Engineering | 2005-2006 |
   | *Lecturer*                | Mechanical and Aerospace Engineering Department  | 2005-2006 |

   Conducted research for regarding the numerical simulation of
   multiphase fluid flow with applications in materials processing,
   fire suppression and contagion spreading, supervised graduate and
   undergraduate research, and taught introductory courses in
   thermodynamics and fluid dynamics. 

** Los Alamos National Laboratory

   | *Graduate Research Assistant* | Computational and Computer Science Division | 2000-2001 |

   Worked with a team on the development of a large-scale multi-physics
   code for the numerical simulation of casting process with specific
   research regarding the elimination of grid induced anisotropy and
   numerically induced spurious currents related to the treatment of
   fluid interfaces. 

** Colorado School of Mines 

   | *Graduate Research Fellow* | Center for Combustion and Environmental Research | 1999-2005 |

   Creation of analytical and numerical models in support of the
   development of a spray based strip casting process in partnership with
   the University of California, Irvine and the Idaho National
   Laboratory, including two and three-dimensional interfacial flow
   solvers with heat transfer and phase change (solidification), an
   analytical model for oblique droplet impact, a Lagrangian spray model,
   and molecular dynamics simulation for the investigation of contact
   line dynamics. 


* EDUCATION

  *Relevant course work* - Numerical Methods, Numerical Solution of PDEs,
  Computational Linear Algebra, Finite Element Methods, Computational
  Fluid Dynamics, Finite Element Methods, Parallel Computing, Discrete
  Element Methods, Atomistic Simulation, Advanced Modeling and
  Simulation, Statistical Methods, Multiphase Flows, Combustion, Surface
  Chemistry, Physical Gas Dynamics, Fluid Mechanics (Introductory,
  Intermediate and Advanced), Heat Transfer, Thermodynamics
  (Introductory and Advanced), Solidification.


** Colorado School of Mines, Golden, CO

   | *Ph.D.* | Engineering Systems - Minor in Computer Science and Applied Mathematics | 2005 |
   Dissertation: Droplet Splash, Spread and Bounce
   GPA: 4.0

** Colorado School of Mines, Golden, CO

   | *M.Sc.* | Engineering Systems | 2001 |
   Thesis: Modeling and Numerical Simulation of Droplet Spreading and Solidification after 
   Impingement on a Cold Substrate
   GPA: 4.0

** Colorado School of Mines, Golden, Co

   | *B.Sc.* | Engineering | 1999 |
   Mechanical Specialty
   GPA: 3.3


* COMPUTING EXPERIENCE

  - Compiled Languages :: C++, Fortran90/2008 , Fortran77, C
  - Interpreted Languages :: Python, Julia, MatLab/Octave, Mathematica
  - Parallelization/HPC :: MPI, OpenMP, OpenCL


* PATENTS AND PUBLICATIONS

** Patents

   S. Madasu and Samuel B. Johnson. Evaluating Fluid Flow in a
   Wellbore. Halliburton Energy Services, Inc., assignee. Patent US
   20130346035 A1. 26 Dec. 2013.  

** Pending Pattent Applications

   S. B. Johnson, A. Lin, D. M. Copeland. Preconditioning a Global Model
   of a Subterranean Region. Halliburton Energy Services, Inc.,
   assignee. Application 14/144/113, 30 Dec. 2013. 

   S. B. Johnson, A. Lin, D. M. Copeland. Preconditioning Distinct
   Subsystem Models in a Subterranean Region Model, Halliburton Energy
   Services, Inc., assignee. Application 14/144,129, 30 Dec. 2013.

   J. Bai, S. B. Johnson, H.G. Walters. Modeling Subterranean Rock
   Blocks In An Injection Treatment Simulation, Halliburton Energy
   Services, Inc., assignee.  Application 13/757,306, 1 Feb. 2013.
   
   S. B. Johnson, H. G. Walters. Simulating an Injection Treatment of a
   Subterranean Zone, Halliburton Energy Services, Inc.,
   assignee. Application 13/757,052, 1 Feb. 2013. 
 
** BOOK CHAPTERS AND ARTICLES

   J-P Delplanque, S. B. Johnson, L. L. Shaw, and Y. Zhou, Spray
   Deposition and coating processes, in CRC Materials Processing
   Handbook (section on Microstructure change processes),
   Eds. J. R. Groza, E. J. Lavernia, and J. F. Shackelford, CRC, 2006
   (in preparation).

** REFEREED ARCHIVAL PUBLICATIONS
   
   K. M. McHugh, Y. Lin, Y. Zhou, S. B. Johnson, J.-P. Delplanque, and
   E. J. Lavernia, Microstructure Treatment of 2124 Al, Materials
   Science and Engineering A, Vol. 447, pp. 26-34, 2008.

   K. M. McHugh, J-P Delplanque, S. B. Johnson, E. J. Lavernia,
   Y. Zhou, and Y. Lin, Spray Rolling Aluminum Alloy Strip, Materials
   Science and Engineering A, Vol. 383, pp. 96- 106, 2004.

** CONFERENCE PAPERS AND PRESENTATIONS

   S. B. Johnson and J.-P. Delplanque, Seeking an Optimum Droplet Size
   Distribution for Water-Mist Fire Suppression, Paper #07F-44. 2007 Fall
   meeting of the Western States Sections of the Combustion Institute,
   Livermore, CA, October 16 & 17, 2007. 

   S. B. Johnson and J.-P. Delplanque, Estimating Interface Curvature
   for Volume of Fluid Methods, Euromech 479, Sheveningen,
   Netherlands, August 2006. 

   S. B. Johnson and J.-P. Delplanque, Numerical Simulation of
   Parameters Influencing Droplet Rebound, ILASS Americas 19th Annual
   Conference on Liquid Atomization and Spray Systems, Toronto, ON,
   Canada, May 2006. 

   B. Chacon, S. B. Johnson and J.-P. Delplanque, Modeling Droplet
   Spreading on a Solid Substrate from First Contact through Recoil
   with an Energy Conservation Model, ILASS Americas 19 Annual
   Conference on Liquid Atomization and Spray Systems, Toronto, ON,
   Canada, May 2006. 

   S. B. Johnson and J.-P. Delplanque, Resolving Droplet Splashing
   with Adaptive Mesh Refinement and Accurate Curvature Estimation,
   DFD05 58th Annual Meeting Annual Meeting of the American Physical
   Society Division of Fluid Dynamics, November 20-22, 2005, Chicago,
   IL (submitted). 

   S. B. Johnson and J.-P. Delplanque, Analyzing the Results of
   Droplet Impact Simulation by Volume of Fluid Methods: Physics or
   Numerical Errors? ILASS Americas 18th Annual Conference on Liquid
   Atomization and Spray Systems, Irvine, CA, May 2005. 

   A. B. Oliver, S. B. Johnson, J.-P. Delplanque and C. S. Lengsfeld,
   Two Fluid VOF Simulation of Droplet Impact on a Liquid Pool, ILASS
   Americas 18th Annual Conference on Liquid Atomization and Spray
   Systems, Irvine, CA, May 2005. 

   S. B. Johnson, J-P. Delplanque, Y. Lin, Y. Zhou, E. J. Lavernia and
   K. M. McHugh Numerical simulation and experimental characterization
   of a binary aluminum alloy spray - application to the spray rolling
   process, in EPD Congress 2005 - Proceedings of Sessions and
   Symposia Sponsored by the Extraction and Processing Division of The
   Minerals, Metals and Materials Society. 2005 TMS Annual
   Meeting. San Francisco, CA, USA. 13-17 Feb. 2005., pp. 509-517
   (2005). 

   K. M. McHugh, Y. Lin, Y. Zhou, E. J. Lavernia, J.-P. Delplanque and
   S. B. Johnson, Spray rolling aluminum strip for transportation
   applications, in MPMD Sixth Global Innovations Proceedings. Trends
   in Materials and Manufacturing Technologies for Transportation
   Industries and Powder Metallurgy Research and Development in the
   Transportation Industry. Proceedings of Symposium Sponsored by the
   Materials Processing & Manufacturing Division of TMS. 2005 TMS
   Annual Meeting. San Francisco, CA, USA. 13-17 Feb. 2005. 

   S. B. Johnson, J.-P. Delplanque and M. Bussmann, Modeling and
   Simulation of Metal Droplet Impact, Spreading, and Solidification
   on a Solid Substrate, Euromech 450: Studies on Splashes a century
   after A. M. Worthington, Marseille, France, October 27-29, 2004. 

   S. B. Johnson, S. J. Lewis and J.-P. Delplanque, Droplet-Resolved
   Dilute Spray Evaporation Model, 2004 Heat Transfer/Fluids
   Engineering Summer Conference, Charlotte, North Carolina, USA, July
   11-15, 2004. 

   K. M. McHugh, E. J. Lavernia, Y. Zhou, Y. Line, J.-P. Delplanque
   and S. B. Johnson, Aluminum Strip Processing by Spray Rolling,
   Proceedings of the Second International Conference on Spray
   Deposition and Melt Atomization and Fifth International Conference
   on Spray Forming, K. Bauckhage et al. Eds., Bremen, Germany, June
   22-25, Vol. 2, pp. 6.27-6.38, 2003. 

   Y. Lin, Y. Zhou, S. B. Johnson, J.-P. Delplanque, K. M. McHugh and
   E. J. Lavernia, On the Selection of Processing Parameters during
   Spray Rolling Process, Proceedings of the  Second International
   Conference on Spray Deposition and Melt Atomization and Fifth
   International Conference on Spray Forming, K. Bauckhage et
   al. Eds., Bremen, Germany, June 22-25, Vol. 2,
   pp. 7.17-7.30, 2003. 

    
   S. B. Johnson, J.-P. Delplanque, Y. Lin, Y. Zhou, E. J. Lavernia
   and K. M. McHugh, Assisting Spray Rolling Process Development and
   Scale-up with Modeling and Numerical Simulation, Proceedings of the
   Second International Conference on Spray Deposition and Melt
   Atomization and Fifth International Conference on Spray Forming,
   K. Bauckhage et al. Eds., Bremen, Germany, June 22-25, Vol. 2,
   pp. 6.3-6.14, 2003. 
 
   S. B. Johnson, J.-P. Delplanque, E. J. Lavernia, Y. Lin, Y. Zhou
   and K. M. McHugh, Spray Rolling: A Novel Technique for the
   Production of Aluminum Strip, Proceedings of ILASS Americas, 16th
   Annual Conference on Liquid Atomization and Spray Systems,
   Monterey, California, May 18-21, 2003. 

   K. M. McHugh, E. J. Lavernia, Y. Zhou, Y. Lin, J.-P. Delplanque and
   S. B. Johnson, Spray Rolling Aluminum Strip--Process Development
   and Strip Properties, Symposium on Hot Deformation of Aluminum
   Alloys, 132nd Annual Meeting & Exhibition of TMS, San Diego,
   California, March 2-6, 2003. 

   S. B. Johnson, J.-P. Delplanque, E. J. Lavernia, Y. Zhou, Y. Lin
   and K. M. McHugh, Spray Rolling Aluminum Strip: Process Modeling
   and Parametric Studies, Symposium on Hot Deformation of Aluminum
   Alloys, 132nd Annual Meeting & Exhibition of TMS, San Diego,
   California, March 2-6, 2003. 

   S. B. Johnson and J.-P. Delplanque, Simulation Needs in the
   Modeling of Droplet-Based Processes: The case of spray-rolling,
   Presented at the Los Alamos National Laboratory Telluride Workshop,
   Santa Fe, NM, January 21-23, 2003. 

   J.-P. Delplanque and S. B. Johnson, Y. Lin, Y. Zhou, N. Yang,
   K. M. McHugh and E. J. Lavernia, Using CFD Simulations to Improve
   Spray-Based Materials Processes, 2002 International Conference on
   Process Modeling in Powder Metallurgy & Particulate Materials,
   October 28-29, 2002, Newport Beach, California. 

   S. B. Johnson, Y. Lin, Y. Zhou, J.-P. Delplanque, K. M. McHugh, and
   E. J. Lavernia, Modeling and Simulation of the Spray Rolling
   Process, 2002 International Conference on Process Modeling in
   Powder Metallurgy & Particulate Materials, October 28-29, 2002,
   Newport Beach, California. 

   S. B. Johnson and J.-P. Delplanque, Modeling the Spray-Rolling
   Process: from droplets to spray, 39th Annual Technical Meeting of
   the Society of Engineering Science, Penn State University, PA,
   October 13-16th, 2002. 

   S. B. Johnson and J.-P. Delplanque, Micro-Scale Aspects of Spray
   Deposition Processing: A semi-Analytical Model for Droplet Spreading
   and Solidification at Off-Normal Impact Angles, 2000 ASME IMECE,
   November 5-10, 2000 Orlando, FL, session on Transport Phenomena in
   Spray and Coating Processes HTD-Vol. 366-3, Proceedings of the ASME
   Heat Transfer Division, Vol. 3, pp. 381-271-388, ASME 2000. 

** Other Publications

   S. B. Johnson, Droplet Spread, Rebound and Splash,
   Ph. D. Dissertation, Colorado School of Mines, Engineering
   Division, 2005. 

   S. B. Johnson, Modeling and Numerical Simulation of Droplet
   Spreading and Solidification after Impinging on a Solid Substrate,
   Master of Science Thesis, Colorado School of Mines, Engineering
   Division, 2005. 

